version: '3.7'

services:

  prisma:
    image: prismagraphql/prisma:1.34
    networks:
      - prisma-tier
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma

  postgres:
    image: postgres:10.3
    restart: always
    networks:
      - prisma-tier
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - "db-data:/var/lib/postgresql/data"

  server:
    container_name: dashboard-prod
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - prisma-tier

  back-end-prod:
    container_name: back-end-prod
    build:
      context: ./back-end
      dockerfile: Dockerfile
    networks:
      - prisma-tier
    ports:
      - '4000:4000'

networks:
  prisma-tier:

volumes:
  db-data: ~
